#149: added test function
metno/py-mmd-tools pull request #150
Opened 2022-04-29 10:57 UTC by johtoblan

**Summary**:

**Related issue**: 

Closes #149 

**Suggested reviewer(s)**:

**Reviewer checklist**:

- [ ] The headers of all files contain a reference to the repository license (i.e., "License: This file is part of py-mmd-tools, licensed under the Apache License 2.0 (https://www.apache.org/licenses/LICENSE-2.0)")
- [ ] 100% test coverage of new code - meaning:
    - [ ] The overall test coverage increased or remained the same as before
    - [ ] Every function is accompanied with a test suite
    - [ ] Tests are both positive (testing that the function work as intended with valid data) and negative (testing that the function behaves as expected with invalid data, e.g., that correct exceptions are thrown)
    - [ ] Functions with optional arguments have separate tests for all options
- [ ] Examples are supported by doctests
- [ ] All tests are passing
- [ ] All names (e.g., files, classes, functions, variables) are explicit
- [ ] Documentation (as docstrings) is complete and understandable

The checklist is based on the S-ENDA conventions and definition of done (see https://s-enda-documentation.readthedocs.io/en/latest/general_conventions.html). The above points are not necessarily relevant to all contributions. In that case, please add a short explanation to help the reviewer.

2022-04-29 15:48 UTC, mortenwh requested changes
Is the warning needed? Apart from that, it looks good to me :)

2022-05-02 10:29 UTC, mortenwh reviewed
I made some more changes. Yours look fine but can you review mine?

2022-05-02 10:30 UTC, mortenwh approved these changes

2022-05-02 10:43 UTC, johtoblan reviewed
LGTM

2022-05-02 10:46 UTC, merged