Handle acdd attribute project in format "Some Project Name (SPN)"
metno/py-mmd-tools pull request #252
Opened 2023-04-21 13:22 UTC by TAlonglong

**Summary**:

**Related issue**: 
closses #247 

**Suggested reviewer(s)**:

**Reviewer checklist**:

- [ ] The headers of all files contain a reference to the repository license (i.e., "License: This file is part of py-mmd-tools, licensed under the Apache License 2.0 (https://www.apache.org/licenses/LICENSE-2.0)")
- [ ] 100% test coverage of new code - meaning:
    - [ ] The overall test coverage increased or remained the same as before
    - [ ] Every function is accompanied with a test suite
    - [ ] Tests are both positive (testing that the function work as intended with valid data) and negative (testing that the function behaves as expected with invalid data, e.g., that correct exceptions are thrown)
    - [ ] Functions with optional arguments have separate tests for all options
- [ ] Examples are supported by doctests
- [ ] All tests are passing
- [ ] All names (e.g., files, classes, functions, variables) are explicit
- [ ] Documentation (as docstrings) is complete and understandable

The checklist is based on the S-ENDA conventions and definition of done (see https://s-enda-documentation.readthedocs.io/en/latest/general_conventions.html). The above points are not necessarily relevant to all contributions. In that case, please add a short explanation to help the reviewer.

2023-04-21 13:32 UTC, TAlonglong commented
The tests are failing due to wrong format of the project attribute according to the new setup. Will fix this when we have agreed on the details.

2023-04-25 08:51 UTC, TAlonglong commented
These tests are also failing. Blocked by https://github.com/metno/mmd/pull/217

2023-04-27 10:24 UTC, johtoblan approved these changes
LGTM

2023-04-28 07:55 UTC, mortenwh commented
For the documentation - maybe the update could be done here. The project field in `mmd_elements.yaml` (https://github.com/metno/py-mmd-tools/blob/75c1d2893f2cd36ab50ca4043929709dcb730766/py_mmd_tools/mmd_elements.yaml#L447) needs to be updated, and then the DMH should be checked. Could be done as a separate issue as well but it is kind of urgent if the solution is not backward compatible.

2023-04-28 12:28 UTC, TAlonglong commented
OK, so the short_name section should be remove. And update the long_name description.

2023-05-03 11:01 UTC, TAlonglong commented
OK, I think I have it OK. But please have a look to ensure the implementation is as expected.

2023-05-04 07:54 UTC, mortenwh requested changes

2023-05-04 07:54 UTC, mortenwh commented on py_mmd_tools/mmd_elements.yaml
> +    comment: Comma separated list.
```suggestion
```

2023-05-04 07:54 UTC, mortenwh commented on py_mmd_tools/mmd_elements.yaml
> +        description: The name of the project(s) principally responsible for originating this data in the format <long projectname> (<short project name>). Multiple projects can be separated by commas
```suggestion
```

2023-05-04 07:54 UTC, mortenwh commented on py_mmd_tools/mmd_elements.yaml
>        project:
```suggestion
```

2023-05-04 07:54 UTC, mortenwh commented on py_mmd_tools/mmd_elements.yaml
>    minOccurs: '0'
```suggestion
  minOccurs: '0'
  acdd: 
      project:
          separator: ','
          comment: Comma separated list.
          description: The name of the project(s) principally responsible for originating this data in the format <long projectname> (<short project name>). Multiple projects can be separated by commas, as described under Attribute Content Guidelines. Examples; 'PATMOS-X', 'Extended Continental Shelf Project' becomes 'Extended Continental Shelf Project (PATMOS-X)'. I.e., if each substring includes a keyword in parantheses, the content within the paranthesis is interpreted as the short name for the project while the rest is the long name, e.g., 'Nansen Legacy (NLEG)'.
```

2023-05-04 12:26 UTC, TAlonglong commented
var en liten detalj i get_project som manglet. Fikset det og.

2023-05-08 17:52 UTC, mortenwh commented
`tests/test_nc_to_mmd.py::test_create_mmd_1 - assert False is True`

I don't understand why the online tests are passing but I'll try to figure out of it...

2023-05-09 06:34 UTC, mortenwh approved these changes

2023-05-09 06:35 UTC, merged